### ISSUE TITLE
Some aw-dispatch-alist keys trigger a `No such candidate` error

### ISSUE THREAD

**Issue by mtourne** [abo-abo/ace-window#92] opened 2017-05-18 18:55 UTC
I've set 
`(global-set-key (kbd "M-c") 'ace-window)`

and; I'm a dvorak typist :
`(setq aw-keys '(?a ?o ?e ?u ?i ?1 ?2 ?3 ?4 ?5))`  

my slightly customized dispatch alist is as such :
```
(defvar aw-dispatch-alist
  '((?x aw-delete-window " Ace - Delete Window")
    (?s aw-swap-window " Ace - Swap Window")
    (?p aw-flip-window " Ace - Previous window")
    (?v aw-split-window-vert " Ace - Split Vert Window")
    (?h aw-split-window-horz " Ace - Split Horz Window")
    (?m delete-other-windows " Ace - Maximize curr Window")
    )
  "List of actions for `aw-dispatch-default'.")
```

When hitting `M-c`, and then `h` I'm getting : `No such candidate, 104`

**Comment by abo-abo** [comment] 2017-05-18 19:13
Works fine for me.

**Comment by abo-abo** [comment] 2017-05-18 19:13
Maybe you pressed `hh`?

**Comment by mtourne** [comment] 2017-05-18 22:19
No, this is consistently reproducible. 

For info it's the latest version of Emacs for osx (25.2), available here : https://emacsformacosx.com/

**Comment by rswgnu** [comment] 2017-12-11 22:33
Works fine here with the latest release as well.  What probably happened is that he did an interactive eval-last-sexp over the defvar, which unfortunately leaves it unchanged in Emacs since it is already set.  The original aw-dispatch-alist does not have an 'h' command entry, so he received the error.  (To interactively eval an already set defvar, you have to move inside of the defvar and use C-M-x (which is eval-defun)).

You should close this issue.

**Comment by abo-abo** [comment] 2017-12-12 21:20
@mtourne Can you still reproduce? Please provide the steps with `emacs -Q`.

**Comment by shusso** [comment] 2018-06-27 15:59
Uninstalling `0.9.0 (melpa-stable)` and installing `20180607.1223 (melpa)` fixed this issue for me.

**Comment by abo-abo** [comment] 2018-06-28 10:36
Thanks for the info, closing.

**Closed by abo-abo** 2018-06-28 10:36 UTC
