### ISSUE TITLE
ace-window break helm-mini

### ISSUE THREAD

**Issue by azzamsa** [abo-abo/ace-window#164] opened 2019-02-15 08:14 UTC
Hi

Ace-window will break helm-mini if I select it using ace-window. The gif below explain how to reproduce the error.

1) Tried to use arrow/ret in helm-mini : broken
2) Tried to type command in helm-mini : broken
3) select minibuffer (not helm-mini) : works.

![helm](https://user-images.githubusercontent.com/17734314/52843299-4a880780-3134-11e9-8a37-76b2a1760bcd.gif)

If 'helm-mini' is not buffer per se. maybe we can just ignore it from ace-window selection.

Thank you.

**Comment by abo-abo** [comment] 2019-02-19 10:59
This is expected behavior: `*helm-mini*` is just a regular buffer that you can interact with.
Sometimes it makes sense to select it, e.g. if you want to copy a word from there. You can always switch back from `*helm-mini*` to the minibuffer to continue with completion.

Closing as not a bug.

**Closed by abo-abo** 2019-02-19 10:59 UTC

**Comment by azzamsa** [comment] 2019-02-19 11:25
Oh, I see.

Thank you a ton for ace-window :).

**Comment by abo-abo** [comment] 2019-02-19 11:29
You're welcome)
