### ISSUE TITLE
Horizontally scrolled buffers show no numbers

### ISSUE THREAD

**Issue by Eeemil** [abo-abo/ace-window#142] opened 2018-10-16 13:23 UTC
When a buffer for some reason is horizontally scrolled a bit to the right, the number indicating what window to jump to disappears.
This happens for instance when my screen resolution is changed on my computer and Emacs gets confused.

A simple way of reproducing my screenshot:
1. Start Emacs (GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21)
 of 2017-09-22, modified by Debian)
2. Add two new windows (`C-x 3` `C-x 2`)
3. Move to any window, create a new buffer (`C-x b asdf`) and enter a really long line.
4. Scroll a bit to the right (E.g by using `M-x horizontal-scroll-bar-mode`)
5. `M-x ace-window`
![screenshot from 2018-10-16 15-15-35](https://user-images.githubusercontent.com/7189109/47019315-120cf880-d157-11e8-9c14-3eebd36bde69.png)

**Comment by abo-abo** [comment] 2019-02-04 13:44
I think this is related to customizing `aw-leading-char-face` height. This was recently fixed. Please test if the issue is still reproducible.

**Comment by Eeemil** [comment] 2019-02-05 08:37
Sorry, using `ace-window-20190204.1347` made no difference.

**Comment by abo-abo** [comment] 2019-02-05 10:02
I still can't reproduce the issue. Please add more detailed steps. And try to reproduce with `make plain` from this repo.

**Comment by rswgnu** [comment] 2019-02-19 12:07
The latest commit should have resolved this issue.

**Comment by Eeemil** [comment] 2019-02-19 13:18
The latest commit fixed this issue for _some_ cases, but introduced errors in other cases.
To reproduce:
1.) Start emacs with welcome-screen
2.) `M-x horizontal-scroll-bar-mode`
3.) Create 3 windows `C-x 3 C-x 3 C-x 3`
4.) Scroll one or more windows to the right
5.) Call `ace-window`

**Comment by gergelypolonkai** [comment] 2019-03-20 07:26
I have a similar, most probably related issue.

1. Have two Emacs windows. In the first window have a buffer with a very short line (even no characters at all) and a very long one. Place point at the end of the long line
2. Switch to the other window and call `ace-window` (i have configured ace-window to activate even if i have only two windows.)

A message appears in the message area: `Beginning of buffer`, while my other window scrolls a few lines in a (seemingly) random direction).

**Comment by rswgnu** [comment] 2019-03-20 11:08
I know about this and the other issue and am working on a fix as I have free time.  I think I have a fix for this one but need to solve the general horizontally scrolled issue also.

**Closed** 2019-03-25 10:28 UTC

**Comment by abo-abo** [comment] 2019-03-25 10:29
Thanks all, please test.

**Comment by Eeemil** [comment] 2019-03-25 14:02
Works like a charm! Thanks @rswgnu and @abo-abo !
