### ISSUE TITLE
Overlay is not displayed when cursor is in the bottom of the window

### ISSUE THREAD

**Issue by pkryger** [abo-abo/ace-window#176] opened 2019-05-21 18:50 UTC
I saw a couple of times that the overlay is not displayed in some windows. The only consistent way I can reproduce it is when the point is in one of the bottom lines and the overlay to be displayed wouldn't fit in the 'first' line. The issue is more pronounced when the leading char is bigger than `1.0`.

Reproduction instruction.
1. Start with a fresh emacs then:
```lisp
(add-to-list 'package-archives (cons "melpa" "http://melpa.org/packages/") t)
(package-initialize)
(package-refresh-contents)
(package-install 'ace-window)
(global-set-key (kbd "M-o") #'ace-window)
(custom-set-faces
 '(aw-leading-char-face ((t (:foreground "red" :bold t :height 2.5)))))
(newline 20)
```
3. Split window: `C-x 2`, `C-x3`
4. Set the points as in the picture (I used mouse):
<img width="703" alt="before" src="https://user-images.githubusercontent.com/815559/58122361-63a3c700-7c01-11e9-87fa-f9c165dd4a9e.png">
5. Hit: `M-o`. Result: 
<img width="703" alt="after" src="https://user-images.githubusercontent.com/815559/58122265-1de6fe80-7c01-11e9-927d-20f6d532b366.png">

Note that I'm using emacs-mac from Mituharu (https://bitbucket.org/mituharu/emacs-mac/src/master/). Not sure if it is possible to scroll half of the line on other versions.

**Comment by abo-abo** [comment] 2019-05-22 15:47
Please test if this was fixed in #175.

**Comment by pkryger** [comment] 2019-05-22 20:16
I started fresh, then followed the steps from the reproduction. After that I overwrote `ace-window.el`:

```bash
$ git rev-parse HEAD
ab0db6a2c3b1c3d9240667df1e1d9cafa2756376
$ cp ace-window.el ../../.emacs.d/elpa/ace-window-20190522.1544/ace-window.el
```
I opened the file and I did `eval-defun` on the new version of the `aw--lead-overlay` from ab0db6a. But it didn't help. The overlay character is still missing for windows where the point is in the bottom area. Please note where the points are in the upper windows:
<img width="703" alt="before2" src="https://user-images.githubusercontent.com/815559/58205270-12b1d280-7cd6-11e9-8cc2-3afeb3aefaf9.png">
After hitting `M-o` the overlay is not displayed:
<img width="703" alt="after2" src="https://user-images.githubusercontent.com/815559/58205295-1fcec180-7cd6-11e9-9b7e-40fa6d87b9d5.png">

**Comment by abo-abo** [comment] 2019-05-22 20:28
> Note that I'm using emacs-mac from Mituharu (https://bitbucket.org/mituharu/emacs-mac/src/master/). Not sure if it is possible to scroll half of the line on other versions.

This could be the cause. Can you try to reproduce with a different Emacs version?

**Comment by pkryger** [comment] 2019-05-23 07:22
That sounded like a reasonable thing to try. I did so. Unfortunately this is still the case. I replied the experiment with [Emacs For Mac OS X](https://emacsformacosx.com/emacs-builds/Emacs-26.2-universal.dmg). Apparently this version cannot display part of the line. Yet the issue remains. Both without and with the ab0db6a patch. Screenshots with the patch applied via `eval-defun`.

![before](https://user-images.githubusercontent.com/815559/58233300-98b03680-7d33-11e9-981d-fd5dde4783e3.png)
![after](https://user-images.githubusercontent.com/815559/58233367-d0b77980-7d33-11e9-9969-08df025b6774.png)

**Comment by abo-abo** [comment] 2019-05-23 09:34
![ace-window-176-1](https://user-images.githubusercontent.com/2937359/58242027-6233e500-7d4e-11e9-8262-832a74547e61.png)

I can't reproduce the issue on GNU Linux, Emacs 26.2. Maybe we can solve it later by using posframe instead of overlays.

**Comment by pkryger** [comment] 2019-05-23 12:43
I just want to confirm: did you have points in the very last line visible in all windows?

BTW: The `asdf` for selection -> my next tweak 👍

**Comment by abo-abo** [comment] 2019-05-23 15:52
> I just want to confirm: did you have points in the very last line visible in all windows?

Yes.

**Comment by pkryger** [comment] 2019-05-23 17:20
I've just done a quick test on a Docker image with `ubuntu:unstable` and their `emacs`. X11 forwarded to `xQuartz`. This time it was GTK (I guess) that drew the frame. Still can't see overlays when I start with the point in the bottom of a window 🤯:

<img width="845" alt="before" src="https://user-images.githubusercontent.com/815559/58272740-14879e80-7d87-11e9-888c-c2bc4569522a.png">
<img width="845" alt="after" src="https://user-images.githubusercontent.com/815559/58272751-19e4e900-7d87-11e9-9688-79ca6dd29ca7.png">

I can share the Docker image if you want.

**Comment by abo-abo** [comment] 2019-05-23 20:39
![ace-window-176-2](https://user-images.githubusercontent.com/2937359/58284727-8f62b080-7dab-11e9-83a7-abc4417f8916.png)

I tried using the same window config and point positions. Still can't reproduce.

**Comment by pkryger** [comment] 2019-05-25 13:11
@abo-abo Could you try with the clean setup? Like literally no other packages nor `.emacs`? Or on a different version of `emacs` (i.e., on `ubuntu:unstable` Docker)? I can see your points 'jump' quite high compared to mine (in frames `a` and `d`). They seem to be about 1/3 from the top, unlike mine that appears to be in the middle of the frame. This happens even if I make the frame full screen on macOS:
![before](https://user-images.githubusercontent.com/815559/58369642-1a9b8d80-7ef5-11e9-9a1b-dc4f1d5a869b.png)
![after](https://user-images.githubusercontent.com/815559/58369643-1d967e00-7ef5-11e9-8699-5cde16eb58e6.png)
Note: the overlay in all frames appears when the point before calling `C-u` is two or more lines above the last visible line (`C-u 2 C-p`). But it does not when it is in the last one or just above.

One extra observation: when I make the leading char face height fairly small, so it fits into the first displayed line the issue is gone. However, workaround like this defeats the fact that I want them to be very visible and easily distinguishable.

**Comment by abo-abo** [comment] 2019-05-27 09:43
There's a way to load ace-window without config from this repo.

    make plain

I tried this one and I still can't reproduce. I add the screenshots of before and after.
![ace-window-176-2](https://user-images.githubusercontent.com/2937359/58411285-3e391200-8074-11e9-8749-b338bba83f37.png)
![ace-window-176-3](https://user-images.githubusercontent.com/2937359/58411286-409b6c00-8074-11e9-8f8f-5239d5120004.png)

**Comment by pkryger** [comment] 2019-05-27 13:11
Thanks for the 'before' shot. I can see that the points in that shot in windows `1` and `2` are in the _firtst_ visible line. Did you move them (i.e, with a mouse click, so the text won't scroll) to the _last_ visible line? I marked example positions, that I use to reproduce, with red arrows:
![58411285-3e391200-8074-11e9-8749-b338bba83f37](https://user-images.githubusercontent.com/815559/58421946-359f0680-8089-11e9-8cb2-4b6e4b36415c.png)

**Comment by abo-abo** [comment] 2019-05-27 13:55
Thanks for the explanation, I was finally able to reproduce. See the commit for the reason. Please test if this is fixed.

**Closed** 2019-05-27 13:55 UTC

**Comment by pkryger** [comment] 2019-05-27 15:25
Thank you - the 138a80c indeed fixes this issue.
